### ISSUE TITLE
[Help]: adding/deleting nodes from nodebalancer config? 

### ISSUE THREAD

**Issue by l8gravely** [linode/ansible_linode#140]
### Description

I'm trying to add a varying number of nodes to a config in a nodebalancer.  But the nodes don't seem to have a 'state: present' or 'state: absent' option according to the docs.  So maybe I'm just clueless, but I don't see how I loop over a list of created linodes (or set facts) and then create a nodebalancer -> config -> node(s) list.  Or even creating multiple configs, each with the same (or differening) numbers of nodes.

Can I pass in an array of node labels when creating a nodebalancer?  

Would something like:

# Create a nodebalancer
---
- name: Create a Linode NodeBalancer
  linode.cloud.nodebalancer:
    label: "{{ nb_label }}"
    region: "{{ nb_region }}"
    tags: nb_tags
    state: present
    configs:
      - port: 80
        protocol: http
        algorithm: roundrobin
        nodes:
          - label: "{{ item.label }}"
            address: "{{ item.IP }}"
    loop:
      private_ips

Where private_ips is a variable defined with set_fact: in another task?

**Comment by l8gravely** [comment]
So I went and looked at the tests for the nodebalancer stuff, and I see that even in the tests you can't just add/remove a node or a config without having to do the entire configuration all over again, but minus the stuff you want to remove.

Why isn't there support for the 'state: absent' flag for these?   Looking at the linode-cli commands, you should be able to remove a single config or node from a config easily.   

I guess maybe I need to start forking the code and hacking on it, but I really don't know anything about writing python code for Ansible modules.    Any hints?

**Comment by LBGarber** [comment]
Hello, thanks for the feedback! I'm sorry to hear the `nodebalancer` module has been causing issues.

I agree that NodeBalancers, configs and nodes should have the ability to be created and updated independently of each-other. Ideally there would be three separate modules for configuring a NodeBalancer: `nodebalancer`, `nodebalancer_config`, and `nodebalancer_config_node` all with their own `state` fields. 

I'll bring this up with my team and see what we can do about getting this implemented.

**Comment by l8gravely** [comment]
>>>>> "Lena" == Lena Garber ***@***.***> writes:

Lena> Hello, thanks for the feedback! I'm sorry to hear the
Lena> nodebalancer module has been causing issues.

Thanks for the followup, I really appreciate it. 

Lena> I agree that NodeBalancers, configs and nodes should have the
Lena> ability to be created and updated independently of
Lena> each-other. Ideally there would be three separate modules for
Lena> configuring a NodeBalancer: nodebalancer, nodebalancer_config,
Lena> and nodebalancer_config_node all with their own state fields.

From my poking around in the linode_api4 python bindings, it does look
like the "state: present" and "absent" flags are supported at the API
level, so you can add/remove nodes.

It's just that the current linode.cloud.nodebalancer: implementation
doesn't support that.  It was quite helpful to look at the tests
directory and see how things are done, but I also don't think your
tests are that representative of the real world, where you build new
linodes, add them to a node balancer config, and then remove a
different node.  All using loops.  :-)

Lena> I'll bring this up with my team and see what we can do about
Lena> getting this implemented.

I'd love to see some examples playbooks which actually do more
real-world work included in the module, and I'd be happy to contribute
my playbooks as a base, assuming of course that what I've written (or
hacked poorly together!) is acceptable.

But having a good tutorial or example to build off of will only
improve the chances of selling more nodebalancers...

I'd do more to help, but I'm really a newbie when it comes to python
hacking, and I spend way too much time learning basics of python
before I can actually make my ideas work.

John

**Comment by LBGarber** [comment]
Hey there! The ability to separately add nodes has been added in [ release `v0.6.0`](https://github.com/linode/ansible_linode/releases/tag/v0.6.0).

At the moment we haven't implemented functionality to independently add configs to a NodeBalancer, but we'll continue investigating adding this in the future.

Let us know if you run into any other issues 🙂
