### ISSUE TITLE
[Bug]: fails to update nodebalancer config on rerun

### ISSUE THREAD

**Issue by sachinr19** [linode/ansible_linode#161]
### Ansible Version

ansible 2.9.6 python version = 3.8.10

### Ansible Configuration

HOST_KEY_CHECKING(~/ansible/ansible.cfg) = False

### Effected Components

nodebalancer

### Expected Behavior

The playbook should only update the changes on rerun.

### Actual Behavior

Running the playbook for a nodeloadbalancer with config first time works perfectly. But upon re-run or updating any value such as eg: check_timeout, causes the below error: 

`failed to create nodebalancer config: 400: Another config is already using port 443`

However this behavior is seen only after adding ssl_cert and ss_key in the conf. Was working fine on protocol: http even on re-runs.
![Screenshot from 2022-06-09 15-06-35](https://user-images.githubusercontent.com/98100840/172776604-cfc61609-1733-409b-983c-48ed24fe2b4a.png)

### Steps to Reproduce

- Create a playbook for nodeloadbalancer
- config:
```    configs:
      - port: 443
        protocol: https
        algorithm: leastconn
        stickiness: table
        check: http
        check_interval: 5
        check_path: /
        check_timeout: 3
        check_attempts: 2
        nodes:
          - label: node01
            address: "{{ node01_PvtIP }}:8080"
          - label: node02
            address: "{{ node02_PvtIP }}:8080"
        ssl_cert: "{{ ssl_cert }}"
        ssl_key: "{{ ssl_key }}"

- Run the playbook and see if the config got created.
- change any value such as check_timeout and run again.
- This will fail with the error `failed to create nodebalancer config: 400: Another config is already using port 443`
![Screenshot from 2022-06-09 15-06-35](https://user-images.githubusercontent.com/98100840/172777417-92e018e2-a882-467c-aa14-20676f657446.png)

**Comment by LBGarber** [comment]
Thanks for the bug report! 🙂 

Looks like this was a simple diffing issue on our end. I've put up a PR to resolve the issue and it should be available in our next patch release. 

Keep in mind that since `ssl_cert` and `ssl_key` are returned as `<REDACTED>` from the Linode API, you'll either need to update another field or use the `recreate` option to apply changes.
