### ISSUE TITLE
[Feature]: image_info - using label filter only returns the first image in the list

### ISSUE THREAD

**Issue by androidwiltron** [linode/ansible_linode#224]
### Description

when using the image_info module and passing in a label as a filter. if there are multiple images with the same label (which is supported by linode) the module should return an array of images. This would mirror the expected behaviour  of the API. 
Currently only the first item in the PaginatedList object from the api is returned.

https://github.com/linode/ansible_linode/blob/b67756a8a39fab6af2707587a4ff107f1345ac38/plugins/modules/image_info.py#L64

An array of image json objects should be returned instead

### New/Affected Components

image_info module

### Example Ansible Config

no change

**Comment by lgarber-akamai** [comment]
Thanks for the feature request!

Generally, our `_info` modules are designed to return a single result that best matches the user-supplied arguments. This use-case seems to fall more in line with an `image_list` module, which we plan to implement in the near future.

I'll keep you updated on when this feature is implemented :slightly_smiling_face:
