### ISSUE TITLE
[Bug]: Need a K8S Read and Write token to see something with lke_cluster_info

### ISSUE THREAD

**Issue by JeGoi** [linode/ansible_linode#261]
### Ansible Version

root@localhost:~/pf-cloud# ansible --version ansible [core 2.14.1]   config file = /root/pf-cloud/ansible.cfg   configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']   ansible python module location = /root/.local/lib/python3.9/site-packages/ansible   ansible collection location = /root/pf-cloud   executable location = /root/.local/bin/ansible   python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/usr/bin/python3)   jinja version = 3.1.2   libyaml = True

### Ansible Configuration

root@localhost:~/pf-cloud# ansible-config dump --only-changed
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names to new standard, use callbacks_enabled instead. This feature will be removed from ansible-core
in version 2.15. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
CALLBACKS_ENABLED(/root/pf-cloud/ansible.cfg) = ['ansible.posix.profile_tasks']
COLLECTIONS_PATHS(/root/pf-cloud/ansible.cfg) = ['/root/pf-cloud']
CONFIG_FILE() = /root/pf-cloud/ansible.cfg
DEFAULT_FORKS(/root/pf-cloud/ansible.cfg) = 50
DEFAULT_HOST_LIST(/root/pf-cloud/ansible.cfg) = ['/root/pf-cloud/inventory']
DEFAULT_ROLES_PATH(/root/pf-cloud/ansible.cfg) = ['/root/pf-cloud/roles']
DEFAULT_STDOUT_CALLBACK(/root/pf-cloud/ansible.cfg) = yaml
HOST_KEY_CHECKING(/root/pf-cloud/ansible.cfg) = False

### Effected Components

https://github.com/linode/ansible_linode/blob/main/docs/modules/lke_cluster_info.md

### Expected Behavior

Have the info like with the read and write
```
failed: [localhost] (item=Token_K8S_R_only) => changed=false
  ansible_loop_var: item
  item: Token_K8S_R_only
  msg: 'Error from Linode API: Your OAuth token is not authorized to use this endpoint.'
ok: [localhost] => (item=Token_K8S_R&W)
```

```
  msg:
    changed: false
    cluster:
      control_plane:
        high_availability: false
      created: '2023-01-13T21:14:28'
      id: BLABLA
      k8s_version: '1.24'
      label: test
      region: ca-central
      status: ready
      tags: []
      updated: '2023-01-13T21:14:28'
      dashboard_url: https://BLABLA.linodelke.net
      failed: false
      kubeconfig: BLABLA
```

### Actual Behavior

```
fatal: [localhost]: FAILED! => changed=false
msg: 'Error from Linode API: Your OAuth token is not authorized to use this endpoint.'
```

### Steps to Reproduce

Create a lke
Create a token limited to read kub
Create a token read and write a kub
Run a simple task:
```
- name: Get info about an LKE cluster by label
  linode.cloud.lke_cluster_info:
    label: 'test'
    api_token: "{{ item }}"
  loop:
  - token_read
  - token_rw
```

**Comment by lgarber-akamai** [comment]
@JeGoi Thanks for the issue report!

I did a bit of digging and was able to reproduce this on my end. In particular, it looks like the `/lke/clusters/{clusterId}/kubeconfig` API endpoint does not currently support tokens with the `lke:read_only` scope.

I'll bring this up internally and get back to you :slightly_smiling_face:
