### ISSUE TITLE
[Question]: About the docs in the collection, and getting to ansbile-galaxy

### ISSUE THREAD

**Issue by t0mk** [linode/ansible_linode#284]
### Description

Hello project devs, namely @lgarber-akamai!

I am now working on an Ansible collection for Equinix, and I'm looking to your project for inspiration. It's one of the most modern Ansible collections for IaaS, and it looks really well done to me.

I see what you have done with module docs. You have "ignored" the community-collection-prescribed format with [DOCUMENTATION, EXAMPLE, and RETURN](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#id9) in the module script, and instead made it more modular and usable with [ansible-specdoc](https://pypi.org/project/ansible-specdoc/) which I see is also a Linode project. I like this approach, it seems better than the prescribed Ansible format.

When you define the docs in such a way, you forfeit the ansible sanity tests (`ansible-test sanity`), because it checks the documentation format. Was this a problem at some point? For example when trying to get your collection to ansible-galaxy.

I understand this is not a matter of an issue, but I figured it's the easiest and least bothersome way to ask. Thanks for your work on the project.

**Comment by lgarber-akamai** [comment]
Hi there @t0mk! 

I appreciate the kind words 🎉 

To answer your question, we do get an `ansible-doc` errors (e.g. `linode.cloud.domain_record_info did not contain a DOCUMENTATION
attribute`) when importing to Ansible Galaxy but it doesn't seem to affect our ability to publish the collection. We also still get code formatting warnings back from Ansible Galaxy (e.g. whitespace issues, unused imports, etc.)

In our original implementation, we automatically generated the `DOCUMENTATION` string using ansible-specdoc and dynamically injected it back into the original module file. This functionality is still present in ansible-specdoc and might come in handy for maintaining a module spec SSOT while also being compliant with all of Ansible's tooling.

That being said, I'd definitely be interested in looking into ways we could become more compatible with some of Ansible's tooling. I'll keep this thread open and will hopefully have some updates to share in the future 👍

**Comment by lgarber-akamai** [comment]
Just adding to the conversation a bit; we've created an example Ansible Collection that uses ansible-specdoc for documentation generation/injection and passes (most) sanity tests: https://github.com/linode/ansible-specdoc-example

**Comment by lgarber-akamai** [comment]
Just closing this out for housekeeping purposes, we can continue this conversation over on the ansible-specdoc repo 🙂
