### ISSUE TITLE
[Bug]: firewall update needs to set empty address lists to None

### ISSUE THREAD

**Issue by marcfiu** [linode/ansible_linode#295]
### Ansible Version

ansible [core 2.11.12]

### Effected Components

firewall.py module

### Expected Behavior

updating a firewall with no IPv6 or IPv4 addresses in a rule should work

### Actual Behavior

Getting "Error from Linode API: Must not be an empty list".

### Steps to Reproduce

- create a firewall with just ipv4 or ipv6 addresses in a rules list
- update the rules with whatever IP version created in previous step
- firewall update will fail with the behavior described above

**Comment by jriddle-linode** [comment]
Thanks for the issue submission, we need to do some research on handling this correctly as the API is expecting something else. I've created a ticket for us to research/fix this.

**Comment by marcfiu** [comment]
Note my one-line fix in the [PR# 296](https://github.com/linode/ansible_linode/pull/296) using None rather than empty [] list did the trick. If that is what the API is expecting, it would be nice to consider if the linode_api4 (-python) module should be systematically managing this correctly on behalf of all its clients rather than each client being exposed to the Linode REST API specific requirements.

**Comment by lgarber-akamai** [comment]
Closing since the corresponding PR has been merged. Feel free to @ me if this issue is still relevant.
