### ISSUE TITLE
[Feature]: Linode reboot

### ISSUE THREAD

**Issue by ricardoklein** [linode/ansible_linode#336]
### Description

Option in _linode.cloud.instance_ to force reboot a linode.

This would be usefull in cases where you use Ansible to apply updates and reboot machines and they hang on booting process.
This then can be used as a _rescue_ action from a _block_.

### New/Affected Components

linode.cloud.instance

### Example Ansible Config

- name: Reboot a Linode instance.
  linode.cloud.instance:
    label: my-linode or id: <linode id>
    state: rebooted or action: reboot

**Comment by lgarber-akamai** [comment]
Thanks for the feature request! I've added a ticket to our internal tracker to implement reboot functionality in the `linode.cloud.instance` module.
