### ISSUE TITLE
[Help]: 

### ISSUE THREAD

**Issue by ajprok** [linode/ansible_linode#382]
### Description

Trying to use the Inventory plugin.

Ran the command:
```
ansible-inventory -i inventories/some_file.yml --list
```

But getting the following error:
```
[WARNING]:  * Failed to parse /some_directories/inventories/some_file.yml with auto plugin: inventory source '/some_directories/inventories/some_file.yml' could not be verified by inventory plugin 'linode.cloud.instance'
[WARNING]: No inventory was parsed, only implicit localhost is available
```

Have installed packages using the following commands:
```
ansible-galaxy collection install linode.cloud
```
```
pip install -r https://raw.githubusercontent.com/linode/ansible_linode/main/requirements.txt
```
Below is the content of some_file.yml
```
plugin: linode.cloud.instance
api_token: <linode-api-token-here>
```

Using Lubuntu OS with python version 3.10.6
Please advise how to proceed.

### Ansible Configuration

CONFIG_FILE() = /etc/ansible/ansible.cfg

**Comment by lgarber-akamai** [comment]
Hello @ajprok , thanks for the issue report!

As a verification step, all inventory files consuming the `linode.cloud.instance` inventory plugin must have one of the following suffixes:

- `linode.yaml`
- `linode.yml`
- `instance.yaml`
- `instance.yml`

https://github.com/linode/ansible_linode/blob/dev/plugins/inventory/instance.py#L264

For example, an inventory file name such as `foo.linode.yml` would be valid but the name `foo.yml` would be invalid.

I understand this does not offer the best user experience, so I will bring up possible ways to improve this functionality or documentation with my team.

**Comment by ajprok** [comment]
@lgarber-akamai Thank you very much for pointing that out.
