### ISSUE TITLE
[Bug]: Galaxy version is inconsistent with GitHub release version

### ISSUE THREAD

**Issue by yzguy** [linode/ansible_linode#393]
### Ansible Version

n/a

### Ansible Configuration

The 0.18.0 version is released on GitHub, but Ansible Galaxy has 0.17.1 listed for the same release.

https://galaxy.ansible.com/linode/cloud
https://github.com/linode/ansible_linode/releases

### Expected Behavior

0.18.0 would be on Galaxy

### Actual Behavior

Galaxy has 0.17.1 for the same release on GitHub

### Steps to Reproduce

Look at GitHub release, look at Galaxy releases

**Comment by jriddle-linode** [comment]
Whoops! Thanks for the issue, I tried to be slick with the version mistake I made, apparently it didn't work.
