### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'polling'

### ISSUE THREAD

**Issue by ajprok** [linode/ansible_linode#419]
### Ansible Version

ansible [core 2.15.4]   config file = /home/ajit/current-projects/lap/lap-infrastructure/configuration/ansible.cfg   configured module search path = ['/home/ajit/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']   ansible python module location = /home/ajit/.local/lib/python3.10/site-packages/ansible   ansible collection location = /home/ajit/.ansible/collections:/usr/share/ansible/collections   executable location = /home/ajit/.local/bin/ansible   python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/home/ajit/current-projects/lap/venv/bin/python3)   jinja version = 3.1.2   libyaml = True

### Ansible Configuration

```
CONFIG_FILE() = /home/ajit/current-projects/lap/lap-infrastructure/configuration/ansible.cfg
DEFAULT_HOST_LIST(/home/ajit/current-projects/lap/lap-infrastructure/configuration/ansible.cfg) = ['/home/ajit/current-projects/lap/lap-infrastructure/configuration/inventory']
DEFAULT_ROLES_PATH(/home/ajit/current-projects/lap/lap-infrastructure/configuration/ansible.cfg) = ['/home/ajit/current-projects/lap/lap-infrastructure/configuration/roles']
HOST_KEY_CHECKING(/home/ajit/current-projects/lap/lap-infrastructure/configuration/ansible.cfg) = False
```

### Effected Components

linode.cloud.firewall_info

### Expected Behavior

I'm using terraform to run an ansible command after instance creation. The ansible command is being run in a virtual environment (**venv**). Following is the relevant code:
```
provisioner "local-exec" {
    working_dir = "${path.root}/../../configuration"
    command = <<EOT
      # Activate venv
      source ../../venv/bin/activate
      # Ansible command
      # Trailing comma in inventory required
      ansible-playbook -i '${self.ip_address},' -e 'gateway=true' -e 'cloud_provider=${var.cloud_provider}' -e 'instance_details=${jsonencode(self)}' init.yml > temp.log
    EOT
  }
```
The output of `pip freeze` is given below:
```
ansible==8.4.0
ansible-core==2.15.4
ansible-specdoc==0.0.14
appdirs==1.4.4
apt-xapian-index==0.49
argcomplete==3.1.2
Babel==2.8.0
baron==0.10.1
blinker==1.4
certifi==2023.7.22
chardet==4.0.0
charset-normalizer==3.2.0
click==8.0.3
colorama==0.4.4
command-not-found==0.3
cryptography==3.4.8
cupshelpers==1.0
dbus-python==1.2.18
defer==1.0.6
distro==1.7.0
distro-info==1.1+ubuntu0.1
galternatives==1.0.8
httplib2==0.20.2
idna==3.4
importlib-metadata==4.6.4
jeepney==0.7.1
Jinja2==3.1.2
keyring==23.5.0
language-selector==0.1
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
linode-api4==5.8.0
livereload==2.6.3
lubuntu-update-notifier==0.4.dev0
Markdown==3.3.6
MarkupSafe==2.1.3
mkdocs==1.1.2
more-itertools==8.10.0
netifaces==0.11.0
oauthlib==3.2.0
olefile==0.46
packaging==21.3
pexpect==4.8.0
Pillow==9.0.1
pipx==1.2.0
polling==0.3.2
psutil==5.9.0
ptyprocess==0.7.0
pycairo==1.20.1
pycups==2.0.1
Pygments==2.11.2
PyGObject==3.42.1
pyinotify==0.9.6
PyJWT==2.3.0
pyparsing==2.4.7
PyQt5==5.15.6
PyQt5-sip==12.9.1
python-apt==2.4.0+ubuntu2
python-debian==0.1.43+ubuntu1.1
pytz==2022.1
pyxdg==0.27
PyYAML==6.0.1
redbaron==0.9.2
reportlab==3.6.8
requests==2.31.0
resolvelib==0.5.4
rply==0.7.8
SecretStorage==3.3.1
six==1.16.0
systemd-python==234
tornado==6.1
types-requests==2.31.0.2
types-urllib3==1.26.25.14
ubuntu-advantage-tools==8001
ubuntu-drivers-common==0.0.0
ufw==0.36.1
unattended-upgrades==0.1
urllib3==2.0.5
usb-creator==0.3.7
userpath==1.9.1
wadllib==1.3.6
xdg==5
xkit==0.0.0
zipp==1.0.0
```
My OS details
```
NAME="Ubuntu 22.04.3 LTS"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
ID_LIKE=debian
```

### Actual Behavior

I get the following error:
```
Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1696018686.9575784-8932-240029338874345/AnsiballZ_firewall_info.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1696018686.9575784-8932-240029338874345/AnsiballZ_firewall_info.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1696018686.9575784-8932-240029338874345/AnsiballZ_firewall_info.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.linode.cloud.plugins.modules.firewall_info', init_globals=dict(_module_fqn='ansible_collections.linode.cloud.plugins.modules.firewall_info', _modlib_path=modlib_path),\r\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_linode.cloud.firewall_info_payload_d7r_jg3b/ansible_linode.cloud.firewall_info_payload.zip/ansible_collections/linode/cloud/plugins/modules/firewall_info.py\", line 12, in <module>\r\n  File \"/tmp/ansible_linode.cloud.firewall_info_payload_d7r_jg3b/ansible_linode.cloud.firewall_info_payload.zip/ansible_collections/linode/cloud/plugins/module_utils/linode_common.py\", line 8, in <module>\r\nModuleNotFoundError: No module named 'polling'\r\n
```

### Steps to Reproduce

Install python.
Install terraform.

In a terminal:
- Create a virtual environment using (**venv**): `python3 -m venv venv`
- Activate venv: `source /path/to/venv/bin/activate`
- Install the packages from requirements.txt: `pip install -r requirements.txt`
- In terraform, create the resource **linode_instance**.
- In the resource section, create the following provisioner
- ``` 
  provisioner "local-exec" {
    working_dir = "${path.root}/../../configuration"
    # command     = "../../venv/bin/python /usr/bin/ansible-playbook -i '${self.ip_address},' -e 'gateway=true' -e 'cloud_provider=${var.cloud_provider}' -e 'instance_details=${jsonencode(self)}' init.yml" # Trailing comma in inventory required
    command = <<EOT
      # Activate venv
      source ../../venv/bin/activate
      # Ansible command
      # Trailing comma in inventory required
      ansible-playbook -i '${self.ip_address},' -e 'gateway=true' -e 'cloud_provider=linode' -e 'instance_details=${jsonencode(self)}' init.yml
    EOT
  }
- Run terraform init in the terraform root folder: `terraform init`
- Run terraform apply: `terraform apply`

**Comment by lgarber-akamai** [comment]
Hello @ajprok, thanks for the report!

The error raised by Ansible suggests that it cannot access your local Python environment. 

If your play is running on the newly provisioned remote host, you will need to install the Python dependencies for the Linode collection on the remote host before running any collection modules: 

```yaml
- apt:
    update_cache: yes
    name: python3-pip
    state: latest

- pip:
    requirements: https://raw.githubusercontent.com/linode/ansible_linode/main/requirements.txt
```

Alternatively, you can use the Linode collection within a separate play that runs on `localhost`.

**Comment by ajprok** [comment]
Thank you for your response @lgarber-akamai. I'm running the playbook on the local host & not the remote host. Please look into this matter. 
Currently, as a work around, I'm directly accessing the linode  api through ansible.

**Comment by ajprok** [comment]
> @ajprok Unfortunately I haven't been able to reproduce this issue quite yet. Is there can chance you could provide a sanitized snippet of the playbook that is encountering this issue?

Please find below an example playbook that encounters the same error:
```
---
- hosts: all
  gather_facts: false
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: "~/.ssh/ansible"
  tasks:
    - name: Test linode firewall_info
      linode.cloud.firewall_info:
        label: "my-firewall"
      register: firewall_info
    - name: Debug
      ansible.builtin.debug:
        msg: "{{ firewall_info }}"
```

Please let me know if you require any log files from my side.

**Comment by lgarber-akamai** [comment]
@ajprok Thanks for the extra info! 

Judging by your playbook, it looks like the `linode.cloud.firewall_info` module will be run on the host passed in through the inventory (`-i`) argument because your `hosts` attribute is set to `all`. Could you try setting it to `localhost` to help narrow down the issue?

**Comment by lgarber-akamai** [comment]
@ajprok Nice, looks like you're past the dependency errors now. 

Judging by the [error](https://github.com/linode/ansible_linode/blob/dev/plugins/modules/firewall_info.py#L120) you're encountering, it looks like the `firewall_info` module is failing to resolve any firewalls with the `my-firewall` label. Could you confirm that this firewall already exists on your account?

**Comment by ajprok** [comment]
> @ajprok Nice, looks like you're past the dependency errors now.
> 
> Judging by the [error](https://github.com/linode/ansible_linode/blob/dev/plugins/modules/firewall_info.py#L120) you're encountering, it looks like the `firewall_info` module is failing to resolve any firewalls with the `my-firewall` label. Could you confirm that this firewall already exists on your account?

After creating the firewall in terraform, and then executing the ansible command, everything seems to work fine. Thank you very much for your support @lgarber-akamai .
However, please update the doc: [https://github.com/linode/ansible_linode/blob/dev/docs/modules/firewall_info.md](https://github.com/linode/ansible_linode/blob/dev/docs/modules/firewall_info.md). 
In the parameters, api_token should show as a required value. For people, not familiar with the ansible collection, it can be confusing.
Once again, thanks.

**Comment by lgarber-akamai** [comment]
@ajprok Happy to help! I'll create a ticket in our internal tracker to improve the documentation around the `api_token` field.

**Comment by ajprok** [comment]
@lgarber-akamai Sorry for the confusion. The issue is still not resolved. I realised that when we change hosts to localhost, the ansible playbook tries to modify my local machine, and not the machine provided in the inventory.

**Comment by lgarber-akamai** [comment]
@ajprok No worries! If you'd like to target your remote host, you'll need to update your playbook to install the necessary Python dependencies on the target host:

```
- apt:
    update_cache: yes
    name: python3-pip
    state: latest

- pip:
    requirements: https://raw.githubusercontent.com/linode/ansible_linode/main/requirements.txt
```

**Comment by ajprok** [comment]
> @ajprok No worries! If you'd like to target your remote host, you'll need to update your playbook to install the necessary Python dependencies on the target host:
> 
> ```
> - apt:
>     update_cache: yes
>     name: python3-pip
>     state: latest
> 
> - pip:
>     requirements: https://raw.githubusercontent.com/linode/ansible_linode/main/requirements.txt
> ```

Thank you for the advice. However, I am now comfortable using the linode api through ansible. Will probably continue that.
