### ISSUE TITLE
[Bug]: Docs for linode.cloud.instance shows parameter firewall_id as supported, attempt to use returns error stating parameter is not supported

### ISSUE THREAD

**Issue by jward238** [linode/ansible_linode#470]
### Ansible Version

2.16.3

### Ansible Configuration

CONFIG_FILE() = /home/$USER/git-repos/ansible-playbooks/deploy-infrastructure/ansible.cfg
DEFAULT_ROLES_PATH(/home/$USER/git-repos/ansible-playbooks/deploy-infrastructure/ansible.cfg) = ['/home/$USER/git-repos/ansible-playbooks/deploy-infrastructure/roles']
DEFAULT_VAULT_PASSWORD_FILE(/home/$USER/git-repos/ansible-playbooks/deploy-infrastructure/ansible.cfg) = /home/$USER/git-repos/ansible-playbooks/deploy-infrastructure/.vault-pass
HOST_KEY_CHECKING(/home/$USER/git-repos/ansible-playbooks/deploy-infrastructure/ansible.cfg) = False

### Effected Components

instance (documentation)

### Expected Behavior

According to documentation the parameter 'firewall_id' should be useable when creating an instance

### Actual Behavior

When using the parameter 'firewall_id' during instance creation, an error is produced stating:

`fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (linode.cloud.instance) module: firewall_id. Supported parameters include: additional_ipv4, api_token, api_version, authorized_keys, backup_id, boot_config_label, booted, configs, disks, group, image, interfaces, label, private_ip, region, root_pass, stackscript_data, stackscript_id, state, tags, type, ua_prefix, wait, wait_timeout."}`

Which indicates the parameter is not supported and the documentation is out of date

### Steps to Reproduce

include the parameter 'firewall_id' when using linode.clod.instance

**Comment by ykim-1** [comment]
Hi @jward238, the latest version should support the attribute. Could you update the Linode Ansible and related packages and try again?

**Comment by jward238** [comment]
Hi @ykim-1 
Looks like it was a python venv issue on my side. Tried what you suggested and there was no change, however I thought I'd destroy my env and rebuild from scratch just in case and now it's working fine.

Not entirely sure what happened but apologies for the false alarm and thank you very much for the fast response!
