### ISSUE TITLE
[Bug]: Documentation bug - document the token scopes required for the api_token for the various modules

### ISSUE THREAD

**Issue by brad2014** [linode/ansible_linode#522]
### Ansible Version

2.17.0

### Effected Components

documentation

### Expected Behavior

I used a api_token that had linodes scope with read/write access, assuming that would be sufficient to create a linode.  It did not work.  After much experiementation, it turns out the module also requires the token to deliver events access (maybe to successfully notice when linode creation is complete).

The required token scope of api_token is not mentioned anywhere.  Please either make a blanket statement in the main [Usage](https://github.com/linode/ansible_linode/blob/dev/README.md#usage) section that the api_token requires full read/write access to all scopes in order to work reliably, or for each module document which scopes are required, and at what access level (in the same way you document which parameters are required).

### Actual Behavior

I had to experiment since the document never mentions api_token scope requirements (as far as I could find).

### Steps to Reproduce

Create a token that only has Linodes read/write access, and then use the linode module to create a linode.
It fails with an error 404.
One might assume that the creation failed, but in fact the linode has been created. 

(my guess: after the linode is creation is initiated, the module waits via event polling  for the creation to complete, and that means the api_token must allow reading events, and maybe other things, which for my api_token failed)

**Comment by ykim-1** [comment]
@brad2014, Thank you for raising this issue! Unfortunately, due to current API limitations, the event token scope is required in this case, and there isn't a straightforward workaround available at the moment. However, we've created an internal tracker to improve documentation on the necessary authentication scopes for each module to better guide the users.
