### ISSUE TITLE
[Help]: 

### ISSUE THREAD

**Issue by onesign12** [linode/ansible_linode#71]
### Description

**I have this error** 

ERROR! couldn't resolve module/action 'linode.cloud.domain_record'. This often indicates a misspelling, missing collection, or incorrect module path.

**task**

  - name: Create a A record
    linode.cloud.domain_record:
      domain: domain.com
      name: "{{ node_name }}"
      type: 'A'
      target: "{{ node_ip }}"
      port: 80
      state: present
    delegate_to: '127.0.0.1'

**ansible-galaxy collection list**

...
vyos.vyos                     2.5.1  
wti.remote                    1.0.1  

/home/mccloud/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 3.7.0  
linode.cloud      0.3.2  

**ansible --version**

ansible [core 2.11.5] 
  config file = /home/mccloud/ansible/ansible.cfg
  configured module search path = ['/home/mccloud/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /home/mccloud/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True

**Comment by LBGarber** [comment]
Hello! 
Support for the `domain` and `domain_record` will be available in the `0.4.0` release later today. I'll let you know once we've cut a release! :smile:

**Comment by LBGarber** [comment]
`linode.cloud 0.4.0` has now been released and pushed to ansible-galaxy!

After upgrading, you should be able to use the `domain` and `domain_record` modules. 

Let me know if you run into any other issues! :smile:
